### ISSUE TITLE
Data gathering is not consistent

### ISSUE THREAD

**Issue by VladDob** [adamboardman/pico-onewire#3]
This library works great. But sometimes the function for gathering the data from the sensor kinda skips a step? I don't know if this is a library problem, a hardware problem or if there is something else in my code that messes up the timing of the functions?
Here is a sample of the results from the serial:
```
Device Address: ffffffffffffffff
Temperature: -1000.0oC
Device Address: 28a16076e0013cdb
Temperature: 29.8oC
Device Address: 28a16076e0013cdb
Temperature: 29.8oC
Device Address: 68a16076e0013cdb
Temperature: -1000.0oC
Device Address: ffffffffffffffff
Temperature: -1000.0oC
Device Address: ffffffffffffffff
Temperature: -1000.0oC
Device Address: ffffffffffffffff
Temperature: -1000.0oC
Device Address: 28a16076e0013cdb
Temperature: 29.8oC
Device Address: 28a16076e0013cdb
Temperature: 29.8oC
Device Address: 68a16076e0013cdb
Temperature: -1000.0oC
match_rom failed
```
As you can see I don't get a consistent reading from the sensor. Sometimes it messes up the address of the sensor, sometimes it says `match rom failed`.

This is generated using the sample code provided in this repo

If you have any idea what might be causing this, i would apreciate the help

**Comment by adamboardman** [comment]
Off the top of my head I think its a hardware issue, either you've not left enough time for the chip to have sampled the temperature before asking for it or your network is too large and your getting interference? I think I was getting a lot less fails with my testing than you are.

**Comment by VladDob** [comment]
How can I leave enough time for the chip to sample the temperature before asking for it? And what do you mean by 'network'?

**Comment by VladDob** [comment]
So i tried playing with the timing of the program and I kept getting the same results. Also, I tried my hardware setup with python too, and the sensor worked great with that, no misses. Also, i had somebody else try my project on their own setup and it worked fine for them. Do you know what might still be causing issues for me?

**Comment by VladDob** [comment]
it was because of Cmake. i had some extra commands in there
